[context.production]
	environment = { REACT_APP_SOLANA_CLUSTER = "mainnet-beta" }
[context.devnet]
	environment = { REACT_APP_SOLANA_CLUSTER = "devnet" }
[context.testnet]
	environment = { REACT_APP_SOLANA_CLUSTER = "testnet" }